### ISSUE TITLE
SetMetricPath 不起效果

### ISSUE THREAD

**Issue by mutoulazy** [penglongli/gin-metrics#1]
当前版本：
github.com/penglongli/gin-metrics v0.1.0

问题情况：
m.SetMetricPath("/metrics") 之后实际访问metrics接口路径还是defaultMetricPath（/debug/metrics）

问题原因：
源码
// SetMetricPath set metricPath property. metricPath is used for Prometheus
// to get gin server monitoring data.
func (m *Monitor) SetMetricPath(path string) {
	m.metricPath = defaultMetricPath
}

是不是应该改为
m.metricPath = path

**Comment by penglongli** [comment]
是的，谢谢提醒~
已经修改，使用 v0.1.1 版本

**Comment by mutoulazy** [comment]
v0.1.1 已验证无此问题
