### ISSUE TITLE
geoip metrics / how to add ?

### ISSUE THREAD

**Issue by lucmichalski** [penglongli/gin-metrics#2]
Hi @penglongli ,

Hope you are all well !

I would like to add some custom metrics from the following middleware:
- https://github.com/cjgiridhar/gin-geo

How should I do it with gin-metrics ?

Thanks for any insights or inputs on that question :-)

Cheers,
Luc Michalski

**Comment by penglongli** [comment]
Hi, i need to understand your needs first.

Do you want to summary CityName/StateCode/CountryCode/ContinentCode by IP-Address?
And exposed these data by custom-metrics ?

**Comment by lucmichalski** [comment]
Context: I am building an acme cdn (content delivery network) with gin/gin-cache and your repo.

So I would like to upgrade the grafana dashboard to use this panel: https://grafana.com/grafana/plugins/grafana-worldmap-panel/ and some others panel for summarizing the activity per city/country/state.

What would be your advice ?

**Comment by penglongli** [comment]
> Context: I am building an acme cdn (content delivery network) with gin/gin-cache and your repo.
> 
> So I would like to upgrade the grafana dashboard to use this panel: https://grafana.com/grafana/plugins/grafana-worldmap-panel/ and some others panel for summarizing the activity per city/country/state.
> 
> What would be your advice ?


Maybe this sample can meet your needs.
```
// 1. Define your custom-metric, and add it to global metrics.
gaugeMetric := &ginmetrics.Metric{
    Type:        ginmetrics.Counter,
    Name:        "summary_country",
    Description: "Summary country/city... by IP Address",
    Labels:      []string{"country", "city", "state"},
}
_ = ginmetrics.GetMonitor().AddMetric(gaugeMetric)

// 2. Set geo interceptor
r.Use(func(ctx *gin.Context) {
    geoResponse, ok := ctx.Get("GeoResponse")
    if ok {
        obj := new(geo.Response)
        if err := json.Unmarshal(geoResponse, obj); err != nil {
            // log err
            // ...
        } else {
            _ = ginmetrics.GetMonitor().GetMetric("summary_country").Inc([]string{
                obj.CountryCode,
                obj.CityName,
                obj.StateCode,
            })
        }
    }
    ctx.Next()
})
```

If the performance of  this geo library is slow, you should consider optimize it.

**Comment by lucmichalski** [comment]
awedsome, I ll try it now :-) 

take care

**Comment by lucmichalski** [comment]
Sorry to re-open it again, but I am stucked to integrate it to grafana... ^^ 

Do you have an idea how to formulate the query in grafana ?

**Comment by penglongli** [comment]
> Sorry to re-open it again, but I am stucked to integrate it to grafana... ^^
> 
> Do you have an idea how to formulate the query in grafana for this panel ?

According to the above, your http_server have metrics. And you can access it with `http://localhost:$port/debug/metrics`, this path will show you the `summary_country` data.

Then, you need to install a `Prometheus`,  configure `Prometheus` to grab these data. After that, you can query the data on `Prometheus`

Grafana is a front dashboard for backend(MySQL/Prometheus/PGSQL...). 

Do you have a `Prometheus` server now?

**Comment by lucmichalski** [comment]
yes, I have setup/dockerized prometheus with grafana ? I already imported your grafana dashboard and wanted to add the world map panel.

**Comment by penglongli** [comment]
> yes, I have setup/dockerized prometheus with grafana. I already imported your grafana dashboard and wanted to add the world map panel.

Yeah,  has any `summary_country` data been query by Prometheus?

**Comment by lucmichalski** [comment]
yes, see the screenshot below:

<img width="1427" alt="Screenshot 2021-04-07 at 08 26 27" src="https://user-images.githubusercontent.com/1963546/113820409-f52b6c00-977a-11eb-9f60-202f9a5192c9.png">

**Comment by penglongli** [comment]
> yes, see the screenshot below:
> 
> <img alt="Screenshot 2021-04-07 at 08 26 27" width="1427" src="https://user-images.githubusercontent.com/1963546/113820409-f52b6c00-977a-11eb-9f60-202f9a5192c9.png">

You can install the plugin for Grafana first: `https://grafana.com/grafana/plugins/grafana-worldmap-panel/?tab=installation`

Download the zip and install plugin.

After `Worldmap Panel` plugin installed, you should create a worldmap panel. And configure it with `Prometheus Query`

**Comment by lucmichalski** [comment]
so the question is, what would like the query because I already installed the plugin :-)

**Comment by penglongli** [comment]
> so the question is, what would like the query because I already installed the plugin :-)

Probably like this,  have an explore~ :)
![image](https://user-images.githubusercontent.com/7887287/113822340-e57a4a80-97af-11eb-8ca6-95097d390574.png)

**Comment by lucmichalski** [comment]
I tried the following but no luck:
``` 
summary_country{job=~"$job", name=~"$city", key=~"$country", latitude=~"$latitude", longitude=~"$longitude"}
```

**Comment by penglongli** [comment]
> summary_country

You can run it in Prometheus first, see whether the grammar is ok.

**Comment by lucmichalski** [comment]
I added longitude, latitude to the metrics as it is required by the panel but it does not display the points as it also needs a metric...

**Comment by penglongli** [comment]
I'll do a test tonight and see how to configure a worldmap panel

Luc Michalski ***@***.***> 于2021年4月7日周三 下午5:01写道：

**Comment by lucmichalski** [comment]
you are just awesome ^^

**Comment by penglongli** [comment]
> you are just awesome ^^

Try with this article: https://www.robustperception.io/using-the-worldmap-panel-with-prometheus

**Comment by penglongli** [comment]
> you are just awesome ^^

I made some fake data. (I don't know why the worldmap not showing up)

![image](https://user-images.githubusercontent.com/7887287/114001938-fd74cb80-988e-11eb-8c96-94daecd6669a.png)

**Comment by lucmichalski** [comment]
Hi @penglongli ,

Hope you are all well !

That's what I managed to get for now:
<img width="1434" alt="Screenshot 2021-04-09 at 06 36 52" src="https://user-images.githubusercontent.com/1963546/114129063-1799c280-98fe-11eb-8b95-289f15280a92.png">

It is not displaying the total count , any ideas mate ?

**Comment by penglongli** [comment]
> count

Don't use `rate` QL, just `summary_country`

**Comment by lucmichalski** [comment]
I tried but I have the following message: 
<img width="725" alt="Screenshot 2021-04-09 at 12 04 48" src="https://user-images.githubusercontent.com/1963546/114164635-cdc7d100-992b-11eb-80f6-dc799769066a.png">

**Comment by penglongli** [comment]
> I tried but I have the following message:
> <img alt="Screenshot 2021-04-09 at 12 04 48" width="725" src="https://user-images.githubusercontent.com/1963546/114164635-cdc7d100-992b-11eb-80f6-dc799769066a.png">

Try `sum(summary_country) by (country)`

**Comment by lucmichalski** [comment]
it works nicely :-)

<img width="1367" alt="Screenshot 2021-04-09 at 14 17 12" src="https://user-images.githubusercontent.com/1963546/114178637-4a63ab00-993e-11eb-8418-6a04f7575b41.png">
