### ISSUE TITLE
Typo fix (README.md file)

### ISSUE THREAD

**Issue by lkaufman-voc** [penglongli/gin-metrics#21]
Hi,
In the bottom part of the README.md file, the section "[Contributing](https://github.com/penglongli/gin-metrics#contributing)", the typos are suggested to be fixed in this sentence:

> "If someone has a problem or suggestions, you can **submit** new issues or new pull **requests**"

- add a word 'submit' (or 'open')
- fix a typo in a word 'requests' in the link to pull requests
Thank you

**Comment by penglongli** [comment]
Thank you Lev. New release v0.1.10 fixed it
