### ISSUE TITLE
How to show URI wise latency timeseries?

### ISSUE THREAD

**Issue by sidchilling** [penglongli/gin-metrics#3]
Hi,

On my grafana dashboard, I want to display a time-series of latencies per URI. How can I do that using gin-metrics?

**Comment by penglongli** [comment]
Reply to you tonight, just configure the Grafana will be okay.

**Comment by penglongli** [comment]
Try with
`histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance, uri))`
