### ISSUE TITLE
How can I add a middleware in metrics path ? 

### ISSUE THREAD

**Issue by AnumSheraz** [penglongli/gin-metrics#4]
I have added a middleware in all of my server routes, that first checks for api-key. If its not valid, then the server returns 404 unauthorised. I want to add this middleware into metricPath /metrics too. The only way ai could think of is, changing the `Use` method in middleware from this;

```
func (m *Monitor) Use(r *gin.Engine) {
	m.initGinMetrics()
	r.Use(m.monitorInterceptor)
	r.GET(m.metricPath, func(ctx *gin.Context) {
		promhttp.Handler().ServeHTTP(ctx.Writer, ctx.Request)
	})
}
```
to
```
func (m *Monitor) Use(r *gin.Engine, middleware gin.HandlerFunc) {
	m.initGinMetrics()
	r.Use(m.monitorInterceptor)
	r.GET(m.metricPath, func(ctx *gin.Context) {
		promhttp.Handler().ServeHTTP(ctx.Writer, ctx.Request)
	}, middleware)
}
```

Is there another way to achieve this ?, or else I am happy to update this library.

**Comment by penglongli** [comment]
I understand that you want to `add authentication` for `/metrics` path.

You can custom define the metrics path, such as `/debug/metrics`. Then `add middleware` for `/debug` preffix.

**Comment by AnumSheraz** [comment]
Does doesn't works either. here is what I've tried;

```
server := gin.Default()
server.GET("/auth", middlewares.CheckApiKey())

m := ginmetrics.GetMonitor()
m.SetMetricPath("/auth/metrics")
m.Use(server)
```

The metrics on path `/auth/metrics` are not going through CheckApiKey middleware. Adding wildcard on server.GET("/auth/*any") make the paths conflict.

`panic: '/metrics' in new path '/auth/metrics' conflicts with existing wildcard '/*any' in existing prefix '/auth/*any'`

**Comment by penglongli** [comment]
> Does doesn't works either. here is what I've tried;
> 
> ```
> server := gin.Default()
> server.GET("/auth", middlewares.CheckApiKey())
> 
> m := ginmetrics.GetMonitor()
> m.SetMetricPath("/auth/metrics")
> m.Use(server)
> ```
> 
> The metrics on path `/auth/metrics` are not going through CheckApiKey middleware. Adding wildcard on server.GET("/auth/*any") make the paths conflict.
> 
> `panic: '/metrics' in new path '/auth/metrics' conflicts with existing wildcard '/*any' in existing prefix '/auth/*any'`

This is a good question!

You can submit a `PullRequest` to change the param `r *gin.Engine` to `r gin.IRoutes`
at [middleware.go#L27](https://github.com/penglongli/gin-metrics/blob/master/ginmetrics/middleware.go#L27)

After that, this code should solve your question:
```
r := gin.Default()

auth := r.Group("/auth", func(ctx *gin.Context) {
    fmt.Println("In auth middleware.")
    ctx.Next()
})

m := ginmetrics.GetMonitor()
m.SetMetricPath("/metrics")
m.Use(auth)

_ = r.Run()
```
Try with [http://localhost:8080/auth/metrics](http://localhost:8080/auth/metrics)

Looking forward to your PullRequest~

**Comment by penglongli** [comment]
Hi, i created a new release `v0.1.2`

You can change this version, and this code will solve your question:
```go
r := gin.Default()

auth := r.Group("/auth", func(ctx *gin.Context) {
    fmt.Println("In auth middleware.")
    ctx.Next()
})

m := ginmetrics.GetMonitor()
m.SetMetricPath("/metrics")
m.Use(auth)

_ = r.Run()

```

**Comment by AnumSheraz** [comment]
I will try it out soon-ish, and let you know :). Thankyou :)

**Comment by AnumSheraz** [comment]
This creates two endpoints 

```
[GIN-debug] GET    /auth/metrics             --> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use.func1 (7 handlers)
[GIN-debug] GET    /metrics                  --> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use.func1 (5 handlers)
```

/auth/metrics is protected with api-key middleware, but /metrics is not.

**Comment by AnumSheraz** [comment]
I've added this middleware as a temporary workaround.

```
func DisableDefaultMetrics(c *gin.Context) {
	if c.Request.RequestURI == "/metrics" {
		c.AbortWithStatusJSON(http.StatusUnauthorized,
			models.TrackError{
				Status: "Failed", ErrorMessage: http.StatusText(http.StatusUnauthorized), StackTrace: []string{""},
			})
		return
	}
}
```

**Comment by penglongli** [comment]
> This creates two endpoints
> 
> ```
> [GIN-debug] GET    /auth/metrics             --> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use.func1 (7 handlers)
> [GIN-debug] GET    /metrics                  --> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use.func1 (5 handlers)
> ```
> 
> /auth/metrics is protected with api-key middleware, but /metrics is not.

My result is :
```bash
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /auth/metrics             --> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use.func1 (5 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2021/06/28 - 20:49:46 | 404 |        2.64µs |       127.0.0.1 | GET      "/metrics"
In auth middleware.
[GIN] 2021/06/28 - 20:51:19 | 200 |     692.453µs |       127.0.0.1 | GET      "/auth/metrics"


```

You can see that the `localhost:8080/metrics` is 404 status. Only `localhost:8080/auth/metrics` is 200 ok.

**Comment by AnumSheraz** [comment]
hm... strange. I must be missing something. but thank you anyways, for quick response and fixes. STAR+1
