### ISSUE TITLE
Is it possible to use with two different routers?

### ISSUE THREAD

**Issue by berabulut** [penglongli/gin-metrics#5]
Hi I am using two different routers in my project. But when i try to use gin-metrics for both of them i get the error below.

`panic: duplicate metrics collector registration attempted
`

My code is similar to this:

```
 func Router1() *gin.Engine {

	r := gin.New()

	m := ginmetrics.GetMonitor()
	m.SetMetricPath("/metrics")
	m.SetSlowTime(10)
	m.SetDuration([]float64{0.1, 0.3, 1.2, 5, 10})
	m.Use(r)

	r.GET("/:key", someFunc())

	return r
 }

```

```
 func Router2() *gin.Engine {

	r := gin.New()


	m := ginmetrics.GetMonitor()
	m.SetMetricPath("/metrics")
	m.SetSlowTime(10)
	m.SetDuration([]float64{0.1, 0.3, 1.2, 5, 10})
	m.Use(r)

	r.GET("/:key", someFunc())

	return r
 }

```

```
func main() {

	g.Go(func() error {
		return routers.Router1().Run(":8080")
	})

	g.Go(func() error {
		return routers.Router2().Run(":8081")
	})

	if err := g.Wait(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by penglongli** [comment]
If you click `ginmetrics.GetMonitor()`, you will see that it's a singleton object.

So you can create object by yourself instead of use `GetMonitor()`.
**Please use v0.1.3 tag**
```go
m := &ginmetrics.Monitor{}
m.SetMetricsPath("/metrics")
m.SetSlowTime(10)
m.SetDuration([]float64{0.1, 0.3, 1.2, 5, 10})

```

do this code for your every gin server

**Comment by berabulut** [comment]
I used v0.1.3 but got `panic: runtime error: invalid memory address or nil pointer dereference`.

**Comment by penglongli** [comment]
> I used v0.1.3 but got
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x30 pc=0x150512d]
> 
> goroutine 25 [running]:
> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).AddMetric(0x0, 0xc0004ac070, 0xc0008178c0, 0x40)    
>         C:/Users/betab/go/pkg/mod/github.com/penglongli/gin-metrics@v0.1.3/ginmetrics/types.go:83 +0x2d     
> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).initGinMetrics(0xc0008178c0)
>         C:/Users/betab/go/pkg/mod/github.com/penglongli/gin-metrics@v0.1.3/ginmetrics/middleware.go:40 +0xc5
> github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use(0xc0008178c0, 0x18c6980, 0xc0002fcd00)
>         C:/Users/betab/go/pkg/mod/github.com/penglongli/gin-metrics@v0.1.3/ginmetrics/middleware.go:28 +0x36
> github.com/berabulut/kapsule/routers.RedirectRouter(0x0)
>         C:/Users/betab/Pictures/kapsule-server/kapsule/routers/routers.go:40 +0x209
> main.main.func2(0x0, 0x0)
>         C:/Users/betab/Pictures/kapsule-server/kapsule/main.go:34 +0x29
> golang.org/x/sync/errgroup.(*Group).Go.func1(0x1d65f40, 0x16cdbe0)
>         C:/Users/betab/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x62
> created by golang.org/x/sync/errgroup.(*Group).Go
>         C:/Users/betab/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x71
> ```
> 
> EDIT: I think i fixed the error above but still getting `panic: duplicate metrics collector registration attempted` .
> 
> Solution was changing global **monitor** variable with **m** in **initGinMetrics** function.
> 
> ```
>   // m was monitor
> 	_ = m.AddMetric(&Metric{ 
> 		Type:        Counter,
> 		Name:        metricRequestTotal,
> 		Description: "all the server received request num.",
> 		Labels:      nil,
> 	})
> ```
> 
> Maybe I should create another project for the other router.

I see that, i will resolve this problem soon.

**Comment by penglongli** [comment]
I‘m sorry that cannot meet your need. Prometheus not allowed do this.

It will panic when prometheus re-register the same metric. The `prometheus` is global singleton.
```
goroutine 7 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc00010c8c0, 0xc000c9e020, 0x1, 0x1)
        /Users/lipenglong/workspace/pratice/vendor/github.com/prometheus/client_golang/prometheus/registry.go:401 +0xb7
github.com/prometheus/client_golang/prometheus.MustRegister(...)
        /Users/lipenglong/workspace/pratice/vendor/github.com/prometheus/client_golang/prometheus/registry.go:178
github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).AddMetric(0xc00039b100, 0xc000c9a000, 0xc00039b100, 0x40)
        /Users/lipenglong/workspace/pratice/vendor/github.com/penglongli/gin-metrics/ginmetrics/types.go:95 +0x1df
github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).initGinMetrics(0xc00039b100)
        /Users/lipenglong/workspace/pratice/vendor/github.com/penglongli/gin-metrics/ginmetrics/middleware.go:40 +0xb2
github.com/penglongli/gin-metrics/ginmetrics.(*Monitor).Use(0xc00039b100, 0x177b0e0, 0xc000197ba0)
        /Users/lipenglong/workspace/pratice/vendor/github.com/penglongli/gin-metrics/ginmetrics/middleware.go:28 +0x2f
main.gin2()
        /Users/lipenglong/workspace/pratice/test-gin/main.go:44 +0x10f
created by main.main
        /Users/lipenglong/workspace/pratice/test-gin/main.go:14 +0x4d


```

**Comment by penglongli** [comment]
I suggest that you can start gin-server separately. But you can write just one repo, with switch param.

**Comment by berabulut** [comment]
Thank's for your help.
