### ISSUE TITLE
能把那个grafana的视图配置给一下不

### ISSUE THREAD

**Issue by xianlubird** [penglongli/gin-metrics#9]
能把那个grafana的视图配置给一下不

**Comment by xianlubird** [comment]
![wecom-temp-b72d548be773f869a52f94de5d862dfc](https://user-images.githubusercontent.com/6504718/130020658-787975f2-fa0b-48a2-992f-a2dfc2b71567.png)

**Comment by penglongli** [comment]
在这里：https://github.com/penglongli/gin-metrics/tree/master/grafana

看 README 记得提前装一个饼图的插件~

**Comment by xuyang404** [comment]
> 在这里：https://github.com/penglongli/gin-metrics/tree/master/grafana
> 
> 看 README 记得提前装一个饼图的插件~

怎么用能说具体点吗？
